# Generated by Django 3.2.20 on 2023-11-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('don_id', models.AutoField(primary_key=True, serialize=False)),
                ('don_name', models.CharField(max_length=50)),
                ('don_description', models.TextField()),
                ('don_attachment', models.ImageField(upload_to='static/')),
                ('don_created_at', models.DateTimeField()),
                ('geom_point', models.TextField(blank=True, null=True)),
                ('has_requests', models.BooleanField()),
                ('request_count', models.IntegerField()),
                ('don_confirmation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donation',
                'managed': False,
            },
        ),
    ]
