# Generated by Django 3.2.20 on 2023-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sponsor_name', models.CharField(max_length=50)),
                ('sponsor_description', models.TextField()),
                ('sponsor_attachment', models.TextField(blank=True, null=True)),
                ('sponsor_created_at', models.DateTimeField()),
                ('geom_point', models.TextField(blank=True, null=True)),
                ('has_requests', models.BooleanField()),
                ('request_count', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sponsor',
                'managed': False,
            },
        ),
    ]
