# Generated by Django 3.2.20 on 2023-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'conversation',
                'managed': False,
            },
        ),
    ]
