# Generated by Django 3.2.20 on 2023-11-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('new_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_name', models.CharField(max_length=100)),
                ('new_description', models.TextField()),
                ('new_subject', models.CharField(blank=True, max_length=70, null=True)),
                ('is_highlighted', models.BooleanField()),
                ('views_count', models.IntegerField(blank=True, null=True)),
                ('new_created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
