# Generated by Django 3.2.20 on 2023-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('administrator_state', models.IntegerField()),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('erase_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
    ]
