# Generated by Django 3.2.20 on 2023-11-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('atta_id', models.AutoField(primary_key=True, serialize=False)),
                ('atta_url', models.TextField()),
            ],
            options={
                'db_table': 'attachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'attachments_event',
                'managed': False,
            },
        ),
    ]
