# Generated by Django 3.2.20 on 2023-09-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('vol_id', models.AutoField(primary_key=True, serialize=False)),
                ('vol_name', models.CharField(max_length=50)),
                ('vol_description', models.TextField()),
                ('vol_attachment', models.TextField(blank=True, null=True)),
                ('vol_created_at', models.DateTimeField()),
                ('geom_point', models.TextField(blank=True, null=True)),
                ('has_requests', models.BooleanField()),
                ('request_count', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('vol_rating', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'volunteer',
                'managed': False,
            },
        ),
    ]
