# Generated by Django 3.2.20 on 2023-09-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('eq_name', models.CharField(max_length=50)),
                ('eq_description', models.TextField()),
                ('eq_created_at', models.DateTimeField()),
                ('geom_point', models.TextField(blank=True, null=True)),
                ('has_requests', models.BooleanField()),
                ('request_count', models.IntegerField()),
                ('don_confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('eq_attachment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medical_equipment',
                'managed': False,
            },
        ),
    ]
